export { default as AdminPanel } from './AdminPanel';
export { default as RiskManagment } from './RiskManagment';
export { default as Vulnerabilities} from './Vulnerabilities';
export { default as Access } from './Access';
export { default as Editor } from './Editor';
export { default as DataControl } from './DataControl';
export { default as ColorPicker } from './Colorpicker';
export { default as TimeTable } from './TimeTable';
export { default as AreaChart } from './Charts/Area';
export { default as BarChart } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as LineChart } from './Charts/Line';
export { default as PieChart } from './Charts/Pie';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';
